version: '3'
services:
  cardano-sl:
    image: cloneearth/cardano-sl-mainnet-wallet:latest
    network_mode: "host"
    ports:
      - "8090:8090"
  daedalus:
    depends_on:
      - cardano-sl
    image: cloneearth/daedalus:latest
    network_mode: "host"
    environment:
      DISPLAY: "$DISPLAY"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
  cardano-sl-explorer-static:
    image: cloneearth/cardano-sl-explorer-static:latest
    volumes:
      - /tmp/explorer:~/
